version: "3.8"
services:
  client:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://demoapi.andyanh.id.vn
      - NEXT_PUBLIC_SITE_URL=https://demo.andyanh.id.vn
    restart: unless-stopped 