version: "3.8"
services:
  client:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://demoapi.andyanh.id.vn
    restart: unless-stopped 